// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJQhSoFrigsktuVoZWV_p0aU1VkgzI8AY',
    appId: '1:993284133979:web:43c3736b5b414dab03db7e',
    messagingSenderId: '993284133979',
    projectId: 'table-for-you-4283a',
    authDomain: 'table-for-you-4283a.firebaseapp.com',
    storageBucket: 'table-for-you-4283a.appspot.com',
    measurementId: 'G-K8SEY4E9P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwlIkUsu1fNAc7K2nSx67euvfMWe4xroQ',
    appId: '1:993284133979:android:358959130e39472803db7e',
    messagingSenderId: '993284133979',
    projectId: 'table-for-you-4283a',
    storageBucket: 'table-for-you-4283a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf9kGRxt3xP_zyPWn4ZSW48IAaKdBhvus',
    appId: '1:993284133979:ios:19801415bf6ffd9203db7e',
    messagingSenderId: '993284133979',
    projectId: 'table-for-you-4283a',
    storageBucket: 'table-for-you-4283a.appspot.com',
    androidClientId: '993284133979-7ngfj1qo29r3krrrdcfls468tmool65j.apps.googleusercontent.com',
    iosClientId: '993284133979-r294vcpkklp22atl9kd0hakefellm5kb.apps.googleusercontent.com',
    iosBundleId: 'com.selectricgo.selectricgoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf9kGRxt3xP_zyPWn4ZSW48IAaKdBhvus',
    appId: '1:993284133979:ios:19801415bf6ffd9203db7e',
    messagingSenderId: '993284133979',
    projectId: 'table-for-you-4283a',
    storageBucket: 'table-for-you-4283a.appspot.com',
    androidClientId: '993284133979-7ngfj1qo29r3krrrdcfls468tmool65j.apps.googleusercontent.com',
    iosClientId: '993284133979-r294vcpkklp22atl9kd0hakefellm5kb.apps.googleusercontent.com',
    iosBundleId: 'com.selectricgo.selectricgoapp',
  );
}
